const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "4",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "5",
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.0,
      numReviews: 20,
      description: "High Quality Product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 100,
      countInStock: 0,
      brand: "Nike",
      rating: 4.9,
      numReviews: 10,
      description: "High Quality Product",
    },
  ],
};

export default data;
